version: "3.9"

services:
  # POSTGRES
  postgres-tf12-container:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-tf12-volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      tf12-network:
        aliases:
          - ${POSTGRES_HOST}

  # NODE (BACKEND)
  node-web-tf12-container:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT}:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres-tf12-container
    networks:
      - tf12-network
    working_dir: /app

  # NGINX (OPCIONAL)
  nginx-tf12-container:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/public
    depends_on:
      - node-web-tf12-container
    networks:
      - tf12-network

networks:
  tf12-network:
    driver: bridge

volumes:
  pgdata-tf12-volume:
  node-modules-tf12-volume:
